기술통계/요약통계: 자료의 내용을 압축하여 설명하는 방법  
정량적인 수치로 전체 데이터의 특징을 요약, 또는 간단한 그래프 사용  
데이터 시각화를 아우르는 이런 데이터 분석방법을 탐색적 데이터 분석

In [ ]:
import gdown
gdown.download("https://bit.ly/3736JW1", "ns_book6.csv", quiet=False)

Downloading...
From: https://bit.ly/3736JW1
To: /content/ns_book6.csv
100%|██████████| 55.0M/55.0M [00:00<00:00, 104MB/s]

'ns_book6.csv'

In [ ]:
import pandas as pd

ns_book6 = pd.read_csv("ns_book6.csv",low_memory=False)
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021.0,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021.0,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021.0,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021.0,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021.0,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

describe(): 기술통계 몇 개 자동 추출

In [ ]:
ns_book6.describe()

                  번호           발행년도           도서권수           대출건수
count  379976.000000  379976.000000  379976.000000  379976.000000
mean   201726.332847    2008.516306       1.135874      11.504629
std    115836.454596       8.780529       0.483343      19.241926
min         1.000000    1947.000000       0.000000       0.000000
25%    102202.750000    2003.000000       1.000000       2.000000
50%    203179.500000    2009.000000       1.000000       6.000000
75%    301630.250000    2015.000000       1.000000      14.000000
max    401681.000000    2650.000000      40.000000    1765.000000

count: 누락된 값을 제외한 데이터 개수  
mean: 평균  
std: 표준편차  
min: 최솟값  
50%: 중앙값  
25% 와 75% 순서대로 늘어 놓았을 때 25% 지점과 75% 지점에 놓ㅇㄴ 값  
max: 최댓값

In [ ]:
sum(ns_book6["도서권수"]==0)

3206

In [ ]:
ns_book7 = ns_book6[ns_book6["도서권수"]>0]

describe(): 기본으로 25%, 50%, 75%  
원하는 위치의 값을 보고 싶으면 30%=0.3 이런 식으로 매개변수 위치지정

In [ ]:
ns_book7.describe(percentiles=[0.3,0.6,0.9])

                  번호           발행년도           도서권수           대출건수
count  376770.000000  376770.000000  376770.000000  376770.000000
mean   202977.476649    2008.460076       1.145540      11.593439
std    115298.245784       8.773148       0.473853      19.279409
min         1.000000    1947.000000       1.000000       0.000000
30%    124649.700000    2004.000000       1.000000       2.000000
50%    204550.500000    2009.000000       1.000000       6.000000
60%    243537.400000    2011.000000       1.000000       8.000000
90%    361341.100000    2018.000000       2.000000      28.000000
max    401681.000000    2650.000000      40.000000    1765.000000

In [ ]:
ns_book7.describe(include="object")

,도서명,저자,출판사,ISBN,세트 ISBN,부가기호,권,주제분류번호,등록일자
count,376770,376770,376770,376770,55866,308252,61793,359792,376770
unique,336408,248850,21875,350810,14875,17,834,12467,4562
top,승정원일기,세종대왕기념사업회 [편],문학동네,9788937430299,9788937460005,0,1,813.6,1970-01-01
freq,250,303,4410,206,702,158235,13282,14816,28185

count: 누락된 값 제외 데이터 개수  
unique:  고유한 값의 개수  
top: 가장 많이 등장하는 값  
freq: top 에 등장하는 항목의 빈도수

평균 = (a + b + c) / 3  
=(x_1 + x_2 + x_3) / 3

In [ ]:
x = [10,20,30]
sum = 0
for i in range(3):
    sum += x[i]
print("평균:", sum / len(x))

평균: 20.0

평균 mean()

In [ ]:
ns_book7["대출건수"].mean()

np.float64(11.593438968070707)

중앙값 median(): 50%

In [ ]:
ns_book7["대출건수"].median()

6.0

In [ ]:
temp_df = pd.DataFrame([1,2,3,4])
temp_df.median()

0    2.5
dtype: float64

데이터 수가 짝수면 가운데 두 개이 값을 평균하여 중앙값 결정

drop_duplicate(): 중복된 값 제거

In [ ]:
ns_book7["대출건수"].drop_duplicates().median()

183.0

중복 없는 대출건수의 중앙값이 높아졌다  
=> 대출건수가 적은 행이 많다

min(): 최솟값  
max(): 최댓값

In [ ]:
ns_book7["대출건수"].min()

0

In [ ]:
ns_book7["대출건수"].max()

1765

분위수: 데이터를 순서대로 늘어 놓았을 때 균등한 간격으로 나누는 기준점  
이분위수: 중앙값 (데이터를 두 구간으로 나누기에)  
사분위수: 25%, 50%, 75% (네 구간으로 나눔)  
각각 1사분위수 2사분위수(중앙값) 3사분위수

quantile(): 분위수 계산

In [ ]:
ns_book7["대출건수"].quantile(0.25)

np.float64(2.0)

In [ ]:
ns_book7["대출건수"].quantile([0.25,0.5,0.75])

0.25     2.0
0.50     6.0
0.75    14.0
Name: 대출건수, dtype: float64

quantile() 각 분위수에 해당하는 값을 담은 시리즈 객체 반환  
시리즈 객체 정의 후 분위수 계산

In [ ]:
pd.Series([1,2,3,4,5]).quantile(0.9)

np.float64(4.6)

interpolation 매개변수에서 중간 값을 계산  
매개변수를 따로 지정하지 않으면 기본 값으로 계산  
interpolation(보간): 두 지점 사이의 특정 위치의 값을 구하는 방법

In [ ]:
4 + (0.9 - 0.75) * (5 - 4) / (1.0 - 0.75)

4.6

위의 방식은
interpolation 매개변수 "linear",   
"midpoint": 분위수 상관 없이 두 수 사이의 중앙값 사용

In [ ]:
pd.Series([1,2,3,4,5]).quantile(0.9, interpolation="midpoint")

np.float64(4.5)

"nearest": 두 수 중에서 가까운 값

In [ ]:
pd.Series([1,2,3,4,5]).quantile(0.9,interpolation="nearest")

np.int64(5)

백분위  
따로 메서드 없음  
10보다 작은지 비교하여 불리언배열 생성

In [ ]:
borrow_10_flag = ns_book7["대출건수"] < 10

변환된 배열에서 True 인 개수를 모두 헤아린 후 전체 데이터 개수로 나누면 10보다 작은 대출건수 비율을 얻을수 있음  
데이터 양이 많으면 10이 위치한 백분위와 비슷하게 됨  
True=1 False+0  
mean(): 평균 구하는 메서드  
10보다 작은 값이 차지하는 비율을 얻을 수 있음

In [ ]:
borrow_10_flag.mean()

np.float64(0.6402712530190833)

In [ ]:
ns_book7["대출건수"].quantile(0.65)

np.float64(10.0)

분산

In [ ]:
ns_book7["대출건수"].var()

371.6956304306922

표준편차

In [ ]:
ns_book7["대출건수"].std()

19.27940949382766

numpy사용

In [ ]:
import numpy as np
diff = ns_book7["대출건수"] - ns_book7["대출건수"].mean()

np.sqrt( np.sum(diff**2) / (len(ns_book7) - 1))

np.float64(19.279409493785508)

최빈값  
가장 많이 등장하는 값
describe(include="object") 출력 중 top 행에 나온 값  
mode(): 최빈값 계산

In [ ]:
ns_book7["도서명"].mode()

0    승정원일기
Name: 도서명, dtype: object

mode()는 텍스트뿐 아니라 수치형에도 적용 가능

In [ ]:
ns_book7["발행년도"].mode()

0    2012.0
Name: 발행년도, dtype: float64

데이터프레임에서 기술통계 구하기  
numeric_only = True 로 지정해야함  
지정하지 않으면 모든 데이터 타입의 열에 대해 수행하기에 시간이 매우 오래 걸리고 경고 발생

In [ ]:
ns_book7.mean(numeric_only=True)

번호      202977.476649
발행년도      2008.460076
도서권수         1.145540
대출건수        11.593439
dtype: float64

ns_book7 번호 열은 모두 고유한 값이기에 최빈값이 의미가 없음  
loc 메서드로 '도서명' 열부터 마지막 열까지 최빈값 찾기

In [ ]:
ns_book7.loc[:,'도서명':].mode()

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,승정원일기,세종대왕기념사업회 [편],문학동네,2012.0,9788937430299,9788937460005,0,1,813.6,1,0,1970-01-01

도서명 열에 가장 많이 등장하는 값은 승정원 일기이고 출판사 열에 가장 많이 등장하는 값은 문학동네다.  
결과값만 보고 승정원일기가 문학동네 출판사의 도서라고 오해하면 안됨  
**mode() 출력 결과물 사이에는 서로 연관 X**

In [ ]:
ns_book7.to_csv('ns_book7.csv',index=False)

csv 파일로 저장